Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.4
Creation-Date: 2015-10-14T15:47:01+03:30

====== Makefile ======
Created چهارشنبه 14 اكتبر 2015


Add a "shebang" at the top of your file:
**#!/bin/bash**

//make -f makefile.win//
//make -f makefile.nix//
**or have a Makefile that contains:**
//win://
//  make -f makefile.win//
//nix://
//  make -f makefile.nix//
and use **make win** or **make nix**





g++  -c   file.cpp   -o   file.o
g++  -o   file.x    file.o

